[package]
name = "mylucid"
version = "0.1.0"
authors = ["Haoran Ma <909475573@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
